version: "3"

networks:
  nginx:
    driver: bridge

services:
  proxy:
    image: nginx:1.25.1
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - nginx
    entrypoint: ["nginx", "-g", "daemon off;"]

  site:
    image: nginx:1.25.1
    container_name: site
    volumes:
      - ./site/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site/code:/var/www/html/site:ro
    networks:
      - nginx
    entrypoint: ["nginx", "-g", "daemon off;"]

  api-blue: &api
    image: node:18.17
    container_name: api-blue
    volumes:
      - ./api:/api
    networks:
      - nginx
    entrypoint: ["node", "/api/index.mjs", "blue"]

  api-green:
    <<: *api
    container_name: api-green
    entrypoint: ["node", "/api/index.mjs", "green"]
